# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Text Title', max_length=100)),
                ('author', models.CharField(default='Author', max_length=50)),
                ('description', models.CharField(default='Description', max_length=150)),
                ('cover_picture', models.ImageField(blank=True, upload_to='media/', verbose_name='img')),
                ('era', models.CharField(choices=[('1', 'Pre-Colonial/Tainos'), ('2', 'Colonial'), ('3', 'Independance War'), ('4', '19th Century'), ('5', '20th Century'), ('6', '21st Century/Modern'), ('7', 'Unknown')], default='Unknown', max_length=255)),
                ('date_posted', models.DateField(auto_now_add=True, verbose_name='Posted on')),
                ('poster', models.CharField(default='Poster', max_length=255)),
                ('slug', models.SlugField(default='slug', max_length=255, unique=True)),
            ],
        ),
    ]
