# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureart',
            name='era',
            field=models.CharField(choices=[('1', 'Pre-Colonial/Tainos'), ('2', 'Colonial'), ('3', 'Independance War'), ('4', '19th Century'), ('5', '20th Century'), ('6', '21st Century/Modern'), ('7', 'Unknown')], default='Unknown', max_length=255),
        ),
    ]
